### ISSUE TITLE
Sustainable and sensible pronoun for nonbinary gender

### ISSUE THREAD

**Issue by Kreyren** [Kreyren/kreyren#79]
Contributions: More references appreciated

---

### Issue
Non-binary people often prefer `they/them` which is confusing as:
1. it's in a plural to refer to the group of people
2. when referring to an invidual who's gender is unknown[1].

In addition to `they/them` people are making up various pronouns such as: Ze, Xen/Xem, Ne/Nhe, etc..

From my personal experience (kreyren) these are often hated by relevant parties who then rather use `she/he`, see motivation below.

### Motivation
Transgender that i care about who prefers non-binary gender hoping to find a solution to make her more comfortable as using un-preferred gender is agains known treatment of gender dysphoria and could be harmful to the mental health[2].

These pronouns are painful to use as:
#### 1. `Ze` (Ze is sitting)
Sound "too german" -> which makes it confusing and painful for those speaking multiple languages.

#### 2. `Xen/Xem` (Xen is sitting)
Confusing as it makes it seem like it's referring to a person called Xen.

#### 3. `Ne/Nhe` (Ne is sitting)
Too similar to verbal "She" while sounding retarded.

### Proposed solution
Define one sustainable and sensible pronoun for nonbinary gender that can be widely used without confusion in verbal or written conversation

### References
1. APA's guidelines to use gender neutral 'they' https://apastyle.apa.org/style-grammar-guidelines/grammar/singular-they
2. Personal research in gender dysphoria https://github.com/kreyren/transgenders
3. RMS's proposal https://web.archive.org/web/20181022225835/https://stallman.org/articles/genderless-pronouns.html

**Comment by rendragon4** [comment]
"Transgender" is only used as an adjective, not a noun."

"Transgender that i care about" -> "Trans person that i care about"

You can also improve the grammar if desired.

**Comment by Kreyren** [comment]
`Trans person` seems weird and offensive to me whats wrong with using it that way?

**Comment by rendragon4** [comment]
My point is that using "transgender" as a noun is generally considered weird and offensive. It's somewhat akin to calling trans people "trannies" but not quite on the same level as a slur.

Using "trans" as a shortened version of the adjective is however commonly done by English native speakers, including trans people.

**Comment by Kreyren** [comment]
> My point is that using "transgender" as a noun is generally considered weird and offensive.

Why?

**Comment by rendragon4** [comment]
"Weird and offensive" may have been too much. I think I was overcompensating because it flabbergasted me that you said the usage of "trans people" seemed weird and office even though it's by far the most common word choice I've encountered from trans people and trans alies.

"Transgender" is an adjective rather than a noun, so using it as a noun may make you seem uninformed, and some people may instinctively assume that because you're uninformed, you don't know how to treat trans people with respect. However, since my original comment I've encountered one instance of a trans person using the word "transgender" like a noun so it may not be as big deal as I thought.

In my opinion, you should simply use others' preferred pronouns per the APA. If you or people in your circles don't like doing so, it's your problem and in my opinion shows that you don't care enough about respecting trans people enough for them to be inclined to willingly tolerate you.

**Comment by Kreyren** [comment]
stale
